[build]
  base = "."
  publish = "./build/"
  command = "npm run build"

[build.processing]
  skip_processing = true

[build.environment]
  NODE_VERSION = "14"
  NPM_VERSION = "7"

[functions]
  directory = "./src/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
